language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install devscripts build-essential lintian dh-make
    - sudo apt-get install qtdeclarative5-dev qt5-default libjack-jackd2-dev
    compiler:
    - clang
    - gcc
    script:
    - echo $TRAVIS_TAG
    # headless server compilation
    - qmake "CONFIG+=headless nosound" Jamulus.pro
    - make
    # normal compilation
    - qmake Jamulus.pro
    - make
    #deploy function is only available in travis-ci.com (not free) but not in travis-ci.org (free)
    #deploy:
    #  provider: releases
    #  api_key:
    #    secure: aQ93/8XU3HEGTif0/rSiF+gcm4uRhyWFdr3Va50BprwQOrZkNg8zIMwIKKODwjLDqxaH4msgNYutcr/VLdLjo4YP43It0UIfv3LGa2VFAkFhuQurMXZlVyx8RhIGLjIaWVWN1GCbNdAQwWNNo2mAkEdRaBrj/26geZotGcYZiztGwTAdy0t/vyYjO1sLZdBKcf7dJ06Pm2ktZO/rDyE4UtCTQiRfqLCKsQ/SILbewOMG/auaSUdU0utsbvXxr+dCzqBPwdSSptWqhIORXORL5oPn6242URzIJkmw5XPwhSabhdbzUjCIN9E24z1vp+cffAohuGXyXXZy9/bGeKa0mXfAaXV+TnJkpMd+i3fN5dY+vhFrlLOpRojRK6NqvaMID6tcNNtZMmFSgaZGyCUJQn4/0X+LdPwvK3/dXY+qElJW62QiJmQAt9OBGcq8EFqQDmEtRivRlbpbERsd/IJoOxP7nI2T00g04uV543ZmhU4fmGw6MVPAlIGRsBECjB0AMTp+3xW3OaUp7jy3WZpZXRrXNI41nZogrxhevPME1BRNk3V+MWQo8R3C+bIaCa5Um/3DZxnMxZgXjI9yzzR7Z8f4RWaQCKjXx41/pk7jxm1TcEyBfRVsb313l/fRLg+fjCmaEnnxu43333XGIv4eIyAGDR8ydF2VpmyP2ejzh8I=
    #  file:
    #  - Jamulus
    #  skip_cleanup: true
    #  on:
    #    repo: corrados/jamulus
    #    tags: true
  - os: osx
    osx_image: xcode11
    before_install:
    - brew install qt5
    - brew link qt5 --force
    script:
    - qmake Jamulus.pro
    - mac/deploy_mac.sh
    #deploy function is only available in travis-ci.com (not free) but not in travis-ci.org (free)
    #deploy:
    #  provider: releases
    #  api_key:
    #    secure: aQ93/8XU3HEGTif0/rSiF+gcm4uRhyWFdr3Va50BprwQOrZkNg8zIMwIKKODwjLDqxaH4msgNYutcr/VLdLjo4YP43It0UIfv3LGa2VFAkFhuQurMXZlVyx8RhIGLjIaWVWN1GCbNdAQwWNNo2mAkEdRaBrj/26geZotGcYZiztGwTAdy0t/vyYjO1sLZdBKcf7dJ06Pm2ktZO/rDyE4UtCTQiRfqLCKsQ/SILbewOMG/auaSUdU0utsbvXxr+dCzqBPwdSSptWqhIORXORL5oPn6242URzIJkmw5XPwhSabhdbzUjCIN9E24z1vp+cffAohuGXyXXZy9/bGeKa0mXfAaXV+TnJkpMd+i3fN5dY+vhFrlLOpRojRK6NqvaMID6tcNNtZMmFSgaZGyCUJQn4/0X+LdPwvK3/dXY+qElJW62QiJmQAt9OBGcq8EFqQDmEtRivRlbpbERsd/IJoOxP7nI2T00g04uV543ZmhU4fmGw6MVPAlIGRsBECjB0AMTp+3xW3OaUp7jy3WZpZXRrXNI41nZogrxhevPME1BRNk3V+MWQo8R3C+bIaCa5Um/3DZxnMxZgXjI9yzzR7Z8f4RWaQCKjXx41/pk7jxm1TcEyBfRVsb313l/fRLg+fjCmaEnnxu43333XGIv4eIyAGDR8ydF2VpmyP2ejzh8I=
    #  file:
    #  - Jamulus.app
    #  skip_cleanup: true
    #  on:
    #    repo: corrados/jamulus
    #    tags: true
  #- os: windows
  #  env:
  #    QT_ACCOUNT_USERNAME and QT_ACCOUNT_PASSWORD variables for Qt registration at install time
  #  - secure: WlWyUMU53vGPwZ340bZZy3PVJJfuFZ8gegyLHGYXo1Hp++BCtHJ5FH2kVYxW0pUNqKobkrlGdNMLrhfDD5qATj6TqbRTQr/XKqK5Qhe8sf7Ag/Z+AUjguED7QL0th2Ll6eBlSc9ayrQfvCjvzmyFXGB85iXvuJlbqUCya6xRyiflq37KimLGjxFOhUkCGsIgraUxUxGm/dLj07x2gH1XeozzSOhX/4uDwlP+y642zWyWf/pOrUTSuid97TJseD9tAmLqFpVo43BqDuCe1/7OmBnZkJQb4obU43KeRAHLUCSnbI+kVVNfW8j0/1ynObngIZoC+KQnvc+4NTU13yRez8HoFcEXa9l9oTRBu+nFu+TM+c8+EBNKDZxrdF2NYLRuNdYIzVqZsbSIT+8aoAwMS+bO9AgW2KCelz7zCSoPRokfM2vH7JPEq7Ofib8neK4MEzAKYL1K0/vDlZktsxX8xIhrzgJQCF8IloMLPR3sKIOckYjBzsQG9Q6QJqC6BKJJSpeN6I6LF6cksSMcUalhsqgCghrLFHalJj0mhkSQGTvXtDr3OOfPSicj1fC3efqjiZ9uT6b5yR2gC9e4NaC0qLcqLuHJL10CUjn2eizKBqr0Onu/ybkkClfBUFzu3uOf8YMq3I1hp4xzkfEPAb1A2Iem6rYA9ndyGUnXrYNoLRs=
  #  - secure: ldDKzVJFDbA1+tJg4jicBTUAzm83mjybEY2hvPxMofE2gBNwAFRj2+XJD5H1tQ/BBE3LADOVRiwiCxZZLSotIChmmrtQJ68tshYTwcpjf+VQ3m59NsHl0xbjP3/B9DYu1zBOhUc43gGsDnRulvzDi8HwbxrM4ACNCepy+zq+a8M7BytddrhZSgIT0rsTBU0t/StH7B/Pu6E6KByelgdmbnZbuAqaT2HMi+IiGrAJiw70Hmq4BgegsEv4kLyNLe2ofZsdvmFw20Gumfg9B4PFM2S0QESj2pPwFgz+uYUgS/0ncpGdFTshnDKPFj7ePgrHT8eM9bMC8BM8RedpoR0vSUyioCxx0YJzSsw8JE8DEe3qNt3HmhPcH678wrYxs3cXLoTC8kBGDPD6drzqBIvILVfPJcaXRJlD7I+GOIkXFojLrxDZRy9I73KbWHGRONLguGBVyqJxGVrPH6hjEAxhgLLMUAnoh61wPFtvnayT+SbWl2NbAewnsjfCNnLgBZOxdmlKMjC5yUH3wnnyBn5jEAHcjrtbSfQ+lD+ZlYmeuimgsvjomHOHKw3N2+tfKW9lAH45ShiiMIMOk9HP9zKnDnyG6hI0q9wPFxWrkc3RZpRmQO1S9QjB2gD3cWiVMNTBYI+XNOqZEUicTc4XwOByf8bm5SyH4H1+8o1RytgbEZY=
  #  before_install:
  #  - curl -vL -o "${TEMP}/qt-installer.exe" http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
  #  - "${TEMP}/qt-installer.exe --verbose --script ./windows/qt-installer-windows.qs"
  #  script:
  #  - powershell -ExecutionPolicy ByPass -Command "./windows/deploy_windows.ps1"
   #deploy function is only available in travis-ci.com (not free) but not in travis-ci.org (free)
   #deploy:
   #  provider: releases
   #  api_key:
   #    secure: aQ93/8XU3HEGTif0/rSiF+gcm4uRhyWFdr3Va50BprwQOrZkNg8zIMwIKKODwjLDqxaH4msgNYutcr/VLdLjo4YP43It0UIfv3LGa2VFAkFhuQurMXZlVyx8RhIGLjIaWVWN1GCbNdAQwWNNo2mAkEdRaBrj/26geZotGcYZiztGwTAdy0t/vyYjO1sLZdBKcf7dJ06Pm2ktZO/rDyE4UtCTQiRfqLCKsQ/SILbewOMG/auaSUdU0utsbvXxr+dCzqBPwdSSptWqhIORXORL5oPn6242URzIJkmw5XPwhSabhdbzUjCIN9E24z1vp+cffAohuGXyXXZy9/bGeKa0mXfAaXV+TnJkpMd+i3fN5dY+vhFrlLOpRojRK6NqvaMID6tcNNtZMmFSgaZGyCUJQn4/0X+LdPwvK3/dXY+qElJW62QiJmQAt9OBGcq8EFqQDmEtRivRlbpbERsd/IJoOxP7nI2T00g04uV543ZmhU4fmGw6MVPAlIGRsBECjB0AMTp+3xW3OaUp7jy3WZpZXRrXNI41nZogrxhevPME1BRNk3V+MWQo8R3C+bIaCa5Um/3DZxnMxZgXjI9yzzR7Z8f4RWaQCKjXx41/pk7jxm1TcEyBfRVsb313l/fRLg+fjCmaEnnxu43333XGIv4eIyAGDR8ydF2VpmyP2ejzh8I=
   #  file:
   #  - Jamulus.exe
   #  skip_cleanup: true
   #  on:
   #    repo: corrados/jamulus
   #    tags: true

